CREATE TABLE apiaries (id TEXT PRIMARY KEY NOT NULL, name TEXT, location TEXT, latitude REAL, longitude REAL, createdAt INTEGER, updatedAt INTEGER);
CREATE TABLE hives (id TEXT PRIMARY KEY NOT NULL, apiaryId TEXT, name TEXT, type TEXT, queenId TEXT, queenYear INTEGER, queenColor TEXT, active INTEGER, notes TEXT, createdAt INTEGER, updatedAt INTEGER, FOREIGN KEY (apiaryId) REFERENCES apiaries(id) ON DELETE CASCADE);
CREATE INDEX idx_hives_apiaryId ON hives(apiaryId);
CREATE TABLE inspections (id TEXT PRIMARY KEY NOT NULL, hiveId TEXT, inspectionDate INTEGER, temperature REAL, strengthEstimate INTEGER, foodStoresKg REAL, broodFrames INTEGER, cappedBroodDm INTEGER, uncappedBroodDm INTEGER, pollenFrames INTEGER, totalFrames INTEGER, queenSeen INTEGER, queenNote TEXT, varroa INTEGER, varroaCount INTEGER, aggression INTEGER, behavior TEXT, notes TEXT, recordingId TEXT, extractedFromAudio INTEGER, createdAt INTEGER, updatedAt INTEGER, FOREIGN KEY (hiveId) REFERENCES hives(id) ON DELETE CASCADE);
CREATE INDEX idx_inspections_hiveId ON inspections(hiveId);
CREATE INDEX idx_inspections_inspectionDate ON inspections(inspectionDate);
CREATE TABLE feedings (id TEXT PRIMARY KEY NOT NULL, hiveId TEXT, feedingDate INTEGER, weightBefore REAL, weightAfter REAL, feedType TEXT, amountKg REAL, notes TEXT, createdAt INTEGER, FOREIGN KEY (hiveId) REFERENCES hives(id) ON DELETE CASCADE);
CREATE INDEX idx_feedings_hiveId ON feedings(hiveId);
CREATE INDEX idx_feedings_feedingDate ON feedings(feedingDate);
CREATE TABLE taxations (id TEXT PRIMARY KEY NOT NULL, hiveId TEXT, taxationDate INTEGER, temperature REAL, totalFrames INTEGER, foodStoresKg REAL, notes TEXT, createdAt INTEGER, updatedAt INTEGER, totalPollenDm INTEGER DEFAULT 0, totalCappedStoresDm INTEGER DEFAULT 0, totalUncappedStoresDm INTEGER DEFAULT 0, totalCappedBroodDm INTEGER DEFAULT 0, totalUncappedBroodDm INTEGER DEFAULT 0, totalStarterFrames INTEGER DEFAULT 0, FOREIGN KEY (hiveId) REFERENCES hives(id) ON DELETE CASCADE);
CREATE INDEX idx_taxations_hiveId ON taxations(hiveId);
CREATE INDEX idx_taxations_taxationDate ON taxations(taxationDate);
CREATE TABLE taxation_frames (id TEXT PRIMARY KEY NOT NULL, taxationId TEXT, position INTEGER, cappedBroodDm INTEGER, uncappedBroodDm INTEGER, pollenDm INTEGER, frameType TEXT, frameYear INTEGER, isStarter INTEGER, hasQueen INTEGER, hasCage INTEGER, hasNucBox INTEGER, notes TEXT, cappedStoresDm INTEGER DEFAULT 0, uncappedStoresDm INTEGER DEFAULT 0, FOREIGN KEY (taxationId) REFERENCES taxations(id) ON DELETE CASCADE);
CREATE INDEX idx_taxation_frames_taxationId ON taxation_frames(taxationId);
CREATE TABLE calendar_events (id TEXT PRIMARY KEY NOT NULL, title TEXT, description TEXT, eventDate INTEGER, eventType TEXT, hiveId TEXT, apiaryId TEXT, completed INTEGER, notes TEXT, createdAt INTEGER);
CREATE INDEX idx_calendar_events_eventDate ON calendar_events(eventDate);
CREATE INDEX idx_calendar_events_hiveId ON calendar_events(hiveId);
CREATE INDEX idx_calendar_events_apiaryId ON calendar_events(apiaryId);
CREATE TABLE settings (key TEXT PRIMARY KEY NOT NULL, value TEXT, updatedAt INTEGER, language TEXT DEFAULT 'sk');
CREATE TABLE inspection_recordings (id TEXT PRIMARY KEY NOT NULL, inspectionId TEXT, filePath TEXT, fileType TEXT, duration INTEGER, fileSize INTEGER, transcription TEXT, extractedJson TEXT, processed INTEGER, recordedAt INTEGER);
CREATE TABLE translations (id TEXT PRIMARY KEY NOT NULL, key TEXT NOT NULL, language TEXT NOT NULL, value TEXT NOT NULL, category TEXT, context TEXT, createdAt INTEGER, updatedAt INTEGER, UNIQUE(key, language));
CREATE INDEX idx_translations_key_language ON translations(key, language);
CREATE INDEX idx_translations_category ON translations(category);
